### ISSUE TITLE
does this support output?

### ISSUE THREAD

**Issue by ddanna** [MyCometG3/DLABridging#1]
Looking to create an app which outputs video to the blackmagic decklink devices. Will this wrapper expose the API for this?

**Comment by MyCometG3** [comment]
Basically, it will. But I did not test this framework with output because I do not have any external recorder.

Also, please see DLABridging/Source/DLABDevice.h - it contains following restrictions line:
/**
 General DeckLink Device object, wrapper of multiple original DeckLink API C++ objects.
 NOTE: Currently following features are not supported.
  : IdeckLinkVideoFrame3DExtensions
  : IDeckLinkAPIInformation
  : IDeckLinkMemoryAllocator
  : IDeckLinkScreenPreviewCallback, IDeckLinkGLScreenPreviewHelper
  : IDeckLinkDeckControl, IDeckLinkDeckControlStatusCallback.
  : Any Encoder related features (compressed packet support).
  : IDeckLinkVideoFrameMetadataExtensions
  : IDeckLinkVideoConversion
 */
@interface DLABDevice : NSObject
:

**Comment by ddanna** [comment]
Is it possible to get a sample of what doing output might look like using this framework? I understand that you can't test it, but a starting point would be immensely helpful.

**Comment by MyCometG3** [comment]
Pre.1. Basic idea is written in Blackmagic Decklink SDK PDF - Chapter 2.4.2 Playback. Please take a look first.

Pre.2. To see swift 4 api interface, use Xcode Assist Editor - Counterparts and check how header files converted to Swift API. Take a look at swift 4 api for:
    DLABDevice.h, DLABBrowser.h,
    DLABVideoSetting.h, DLABAudioSetting.h,
    and DLABConstants.h.

Pre.3. Again, I never debug these API for output because of no recorder device, so If any bug found I welcome another issue report on GitHub.

//

NOTE: your controller class must implement DLABOutputPlaybackDelegate protocol.

1. Prepare Output Device

```
  let browser = DLABBrowser()
  _ = browser.registerDevicesForOutput()
  let deviceList = browser.allDevices
  device = deviceList.first!
```
2. Create Video/Audio output settings

```
    open func createOutputVideoSetting(of mode: DLABDisplayMode, pixelFormat format: DLABPixelFormat, outputFlag videoOutputFlag: DLABVideoOutputFlag, supportedAs displayModeSupportFlag: UnsafeMutablePointer<DLABDisplayModeSupportFlag>) throws -> DLABVideoSetting
    open func createOutputAudioSetting(of type: DLABAudioSampleType, channelCount count: UInt32, sampleRate rate: DLABAudioSampleRate) throws -> DLABAudioSetting
```

3. Enable Video/Audio output AND setup DLABDevice.outputDelegate to your Controller class

```
    open func enableVideoOutput(with setting: DLABVideoSetting) throws
    open func enableAudioOutput(with setting: DLABAudioSetting) throws
    i.e.) device.outputDelegate = self
```

4. Start Audio Preroll

```
    open func beginAudioPreroll() throws
```

5. In Callback for audio queue request Queue Video/Audio Buffer(s) for preroll (Multiple call only for preroll. I guess 4 times each may be enough for preroll)

```
    public func renderAudioSamples(of sender: DLABDevice)
```

```
    open func schedulePlayback(of pixelBuffer: CVPixelBuffer, atTime displayTime: Int, duration frameDuration: Int, inTimeScale timeScale: Int) throws
    open func schedulePlayback(of pixelBuffer: CVPixelBuffer, atTime displayTime: Int, duration frameDuration: Int, inTimeScale timeScale: Int, timecodeSetting setting: DLABTimecodeSetting) throws
    open func schedulePlayback(of audioBufferList: UnsafeMutablePointer<AudioBufferList>, atTime streamTime: Int, inTimeScale timeScale: Int, writtenCount sampleFramesWritten: UnsafeMutablePointer<UInt>) throws
    open func schedulePlayback(ofAudioBlockBuffer blockBuffer: CMBlockBuffer, offset byteOffset: Int, atTime streamTime: Int, inTimeScale timeScale: Int, writtenCount sampleFramesWritten: UnsafeMutablePointer<UInt>) throws
```

6. Finish Audio Preroll

```
    open func endAudioPreroll() throws
```

7. Start Scheduled Playback Stream

```
    open func startScheduledPlayback(atTime startTime: UInt, inTimeScale timeScale: UInt) throws
```

8. When playback delegate func is called Queue next video/audio buffer using schedulePlayback() functions (same funcs above. Both are called for each frame render request)

```
    public func renderVideoFrame(of sender: DLABDevice)
    public func renderAudioSamples(of sender: DLABDevice)
```

9. Stop Scheduled Playback stream using either:

```
    open func stopScheduledPlayback() throws
    open func stopScheduledPlayback(inTimeScale timeScale: Int, atTime stopPlayBackAtTime: Int, actualStopTimeAt actualStopTime: UnsafeMutablePointer<Int>?) throws
```

10. Disable Video/Audio output AND release Device.outputDelegate

```
    open func disableVideoOutput() throws
    open func disableAudioOutput() throws
    i.e.)device.outputDelegate = nil
```
    
11. Release device

```
    deivce = nil
```

//

**Comment by ekiny** [comment]
I'm trying to send video frames to output of decklink card. Most of them are working good but when I run one of these functions which is needed for releasing frames from buffer when user paused the playback, app crashes.
func stopScheduledPlayback() throws
func stopScheduledPlayback(inTimeScale timeScale: Int, atTime stopPlayBackAtTime: Int, actualStopTimeAt actualStopTime: UnsafeMutablePointer<Int>?) throws

**Comment by MyCometG3** [comment]
Thank you for your report. If you don't mind, please consider to raise new issue report instead.

If crash occur under stopScheduledPlayback(), please add actual backtrace for further investigation.
If crash is raised at/after disableVideoOutput/disableAudioOutput, wait scheduledPlaybackHasStopped callback (from DLABOutputPlaybackDelegate protocol) before disale***Output.
