### ISSUE TITLE
DLABDevice+Output  stopScheduledPlayback ERROR

### ISSUE THREAD

**Issue by ekiny** [MyCometG3/DLABridging#17]
I'm trying to send video frames to output of decklink card. Most of them are working good but when I run one of these functions which is needed for releasing frames from buffer when user paused the playback, app crashes.
func stopScheduledPlayback() throws
func stopScheduledPlayback(inTimeScale timeScale: Int, atTime stopPlayBackAtTime: Int, actualStopTimeAt actualStopTime: UnsafeMutablePointer?) throws

stucks on this line : 
[delegate scheduledPlaybackHasStoppedOfDevice:wself]; // async 

inside this function :
- (void)scheduledPlaybackHasStopped

ERROR is : 
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[DLABCapture.OutputManager scheduledPlaybackHasStoppedOfDevice:]: unrecognized selector sent to instance 0x600000135fe0'
and
Thread 10: "-[DLABCapture.OutputManager scheduledPlaybackHasStoppedOfDevice:]: unrecognized selector sent to instance 0x6000036c62b0"

crash is raised before disableVideoOutput/disableAudioOutput.
I had never raised disableVideo functions yet. I'm going step by step.
1. Prepare Output Device
2. Create Video/Audio output settings
3. Enable Video/Audio output AND setup DLABDevice.outputDelegate to your Controller class
4. Start Audio Preroll
5. Queue Video/Audio Buffer(s) for preroll 
6. Finish Audio Preroll
7. Start Scheduled Playback Stream
8. Queue next video/audio buffer using schedulePlayback()
 _**until now everything is working as expected.**_
9. Stop Scheduled Playback stream using either
...

**Comment by MyCometG3** [comment]
I appreciate your new report.

I think it is a bug of DLABOutputPlaybackDelegate protocol implementation in DLABDevice class. 
`- (void)scheduledPlaybackHasStopped` needs to verify that the delegate has `@optional` method before call it.

Please try to implement one of following. it would solve this issue.

1. Implement an optional method in your delegate object as an empty function.
`- (void)scheduledPlaybackHasStoppedOfDevice:(DLABDevice*)sender;`

2. If you can modify the framework code on your side, update DLABDevice+Output.m  as following:
```
- (void)scheduledPlaybackHasStopped
{
    // delegate can schedule next frame here
    __weak typeof(self) wself = self;
    id<DLABOutputPlaybackDelegate> delegate = self.outputDelegate;
    [self delegate_async:^{
        if ([delegate respondsToSelector:@selector(scheduledPlaybackHasStoppedOfDevice:)]) {
        [delegate scheduledPlaybackHasStoppedOfDevice:wself]; // async
        }
    }];
}
```

**Comment by ekiny** [comment]
When I update the code with new one, error is not raising. 
But the problem is:
I call "try device.stopScheduledPlayback(inTimeScale: 24000, atTime: frameCounter, actualStopTimeAt: nil) " for releasing buffer frames on device when I paused the video. stopScheduledPlayback does not releasing frames on device. Am I doing something wrong?

INFO ->>
I searched Decklink SDK for this and found this code lines for releasing video and audio frames (FilePlayback project):
m_deckLinkOutput->StopScheduledPlayback(stopPlaybackAtTime, &stopTime, timeScale);
m_deckLinkOutput->FlushBufferedAudioSamples();

**Comment by MyCometG3** [comment]
Thank you for your response. I am glad to hear that the original crash issue itself is solved now. I would update the master branch later.

Now I have some question. You seem to expect the visual output signal from the decklink device goes to black out or any visual image like "no signal" etc. Is this correct?

As far as I see the SDK pdf, It seems that:
- Device only stops refreshing the visual output with latest buffer - last video signal is "kept online" as final image output.
- Per SDK pdf, audio buffer implicitly released though, video buffer is not documented. I guess they(= Video buffers) are not released at that point, as you said.
- If you want to stop Video "signal output" after schedulingPlayback, you need to call disableVideoOutput/disableAudioOutput (after scheduledPlaybackHasStoppedOfDevice: callback is received). These should release any buffered resources by DeckLink SDK framework.
- Or if you want to refresh video signal with any placeholder image like black screen/no signal image/color bar image, you can force refresh using - instantPlaybackOfPixelBuffer:error: method instead.

I hope this would help your issue.

**Comment by ekiny** [comment]
Thank you for your prompt response. I've made some enhancements to our DLABSandbox SwiftUI project to facilitate better investigation of the issue at hand. Specifically, I've incorporated output classes which I believe will streamline our troubleshooting process.

To access the updated project, please download it from the Google Drive link provided below. Additionally, I've included a test video for playback to help illustrate the problem we're encountering.

[[Google Drive Link]](https://drive.google.com/drive/folders/1lAxJ2hnVewbzAbok2QrUUfp3ZnxMW2et?usp=sharing)

I would greatly appreciate it if you could take some time to review the changes and offer any insights or ideas you may have. Your expertise and collaboration are invaluable as we work towards a resolution.

Thank you once again for your continued effort and support.

**Comment by MyCometG3** [comment]
1.
I think the original crash problem figured by this issue ticket seems to be fixed by above patch. Is this correct?
If so, I would apply the patch into master branch and close this ticket. (The work branch has such update.)

2.
I am afraid if you ask me some code based support of your project... 
Unfortunately I think it is a kind of out-of-scope request.
I am sorry I cannot provide such professional support - I am a kind of Sunday programmer.

3.
Anyway, I can make some comments per your project code.
- I cannot see your updated DLAB SwiftPM code as it is not available in zip archive.
- DLAB itself is under MIT license so you can fork and publish your own version. It is free as you want.
* provided mov file
- Per provided mov file, I found that intermittent empty video frames are observed with proper T/C.
- It could be the implementation issue of prefetch image from source stream.
- It could relate to fps difference (such like 23.976<>24.000) and/or handling dropframe timecode
* Output stream
- DeckLink Frwamework requires the application to specify the exact "source video stream FPS". like DLABDisplayModeHD1080p2398, DLABDisplayModeHD1080p24, etc.
- If your video source depends on different Timecode, FPS+Timecode conversion is your task.
- If your video source has no Timecode, you need to regeneratie your own timecode(s).
- If your video source format and output video format is different, DLAB need to convert image instandly.
- Such like RGB/YUV conversion, or 8bitYUV/10bitYUV conversion, could produce stuttering video stream. 
- DLABDevice.renderVideoFrame(ofDevice:)/.renderAudioSamples(ofDevice:) are the prefetch requests from the DeckLink Framework.
- You need to keep enqueuing multiple video/audio samples in timely manner.
- In other word, I/O Pipeline like input prefetch + format conversion/TC generation + output prefetch should run without any delay.
- DeckLink SDK and DLABDevice support both push model and pull model. Buffering 4 frames or so could improve the stability of output stream.

Thank you for your great effort. I hope this ticket could help your work.
